import { images } from "../images"

export const cabins = {
  title: "客舱",
  subtitle: "选择您在探险船SH Diana上的客舱",
  selectButton: "询价",
  priceNote: "价格为每人每航次",
  categories: [
    {
      name: "Oceanview D4",
      size: "20 m²",
      capacity: "2",
      price: "从 $13,780 起",
      features: [
        "两张单人床或一张双人床",
        "带起居区的卧室",
        "仿真壁炉",
        "豪华浴室",
      ],
      images: [images.cabins.oceanview, images.cabins.oceanview],
    },
    {
      name: "Oceanview M4",
      size: "20 m²",
      capacity: "2",
      price: "候补名单",
      features: [
        "两张单人床或一张双人床",
        "带起居区的卧室",
        "仿真壁炉",
        "豪华浴室",
      ],
      images: [images.cabins.panoramicWindow, images.cabins.panoramicWindow],
    },
    {
      name: "Balcony D5",
      size: "25 m²",
      capacity: "2-3",
      price: "从 $13,780 起",
      features: [
        "5 m² 私人阳台",
        "两张单人床或一张双人床",
        "带起居区的卧室",
        "仿真壁炉",
        "豪华浴室",
      ],
      images: [images.cabins.balcony, images.cabins.balcony],
    },
    {
      name: "Balcony M5",
      size: "25 m²",
      capacity: "2-3",
      price: "从 $13,780 起",
      features: [
        "5 m² 私人阳台",
        "两张单人床或一张双人床",
        "带起居区的卧室",
        "仿真壁炉",
        "豪华浴室",
      ],
      images: [images.cabins.panoramicBalcony, images.cabins.panoramicBalcony],
    },
    {
      name: "Balcony D6",
      size: "25 m²",
      capacity: "2-3",
      price: "从 $13,780 起",
      features: [
        "5 m² 私人阳台",
        "两张单人床或一张双人床",
        "带起居区的卧室",
        "仿真壁炉",
        "豪华浴室",
      ],
      images: [images.cabins.balcony, images.cabins.balcony],
    },
    {
      name: "Junior Suite",
      size: "32-36 m²",
      capacity: "2",
      price: "从 $23,380 起",
      features: [
        "6 m² 私人阳台",
        "特大号床",
        "独立起居区",
        "豪华套内浴室",
      ],
      images: [images.cabins.juniorSuite, images.cabins.juniorSuite],
    },
    {
      name: "Suite",
      size: "41 m²",
      capacity: "2-3",
      price: "从 $27,280 起",
      features: [
        "5 m² 私人阳台",
        "特大号床",
        "独立起居室",
        "仿真壁炉",
        "带独立浴缸和步入式淋浴的豪华套内浴室",
      ],
      images: [images.cabins.suite, images.cabins.suite],
    },
    {
      name: "Premium Suite",
      size: "41 m²",
      capacity: "2",
      price: "从 $31,180 起",
      features: [
        "8 m² 私人阳台",
        "特大号床",
        "独立起居室",
        "仿真壁炉",
        "带独立浴缸和淋浴的豪华套内浴室",
        "步入式衣柜",
      ],
      images: [images.cabins.premiumSuite, images.cabins.premiumSuite],
    },
  ],
} as const
