import { images } from "./images"

export const cabins = {
  title: "Cabins",
  subtitle: "Choose your cabin aboard the expedition vessel SH Diana",
  popularBadge: "Popular choice",
  selectButton: "Request a quote",
  categories: [
    {
      name: "Oceanview Cabin",
      size: "20 m²",
      features: ["Two portholes", "Twin or double bed", "En-suite bathroom", "Smart TV", "Mini-bar"],
      image: images.cabins.oceanview,
      featured: false,
    },
    {
      name: "Panoramic Window Cabin",
      size: "20 m²",
      features: [
        "Large panoramic window",
        "Twin or double bed",
        "En-suite bathroom",
        "Smart TV",
        "Mini-bar",
      ],
      image: images.cabins.panoramicWindow,
      featured: false,
    },
    {
      name: "Balcony Cabin",
      size: "25 m²",
      features: [
        "Private balcony",
        "Twin or double bed",
        "En-suite bathroom with shower",
        "Smart TV",
        "Mini-bar",
        "Seating area",
      ],
      image: images.cabins.balcony,
      featured: true,
    },
    {
      name: "Panoramic Balcony Cabin",
      size: "25 m²",
      features: [
        "Panoramic balcony",
        "Twin or double bed",
        "Premium bathroom",
        "Smart TV",
        "Mini-bar",
        "Workspace",
      ],
      image: images.cabins.panoramicBalcony,
      featured: true,
    },
    {
      name: "Junior Suite with Panoramic Balcony",
      size: "32–36 m²",
      features: [
        "Spacious panoramic balcony",
        "Separate living area",
        "King-size bed",
        "Luxurious bathroom",
        "Smart TV",
        "Coffee machine",
        "Bathrobe and slippers",
      ],
      image: images.cabins.juniorSuite,
      featured: true,
    },
    {
      name: "Suite with Panoramic Balcony",
      size: "41 m²",
      features: [
        "Large panoramic balcony",
        "Separate bedroom and living room",
        "King-size bed",
        "Marble bathroom with bathtub",
        "Smart TV in each room",
        "Nespresso machine",
        "Premium amenities",
      ],
      image: images.cabins.suite,
      featured: true,
    },
    {
      name: "Premium Suite with Panoramic Balcony",
      size: "41 m²",
      features: [
        "Expansive panoramic balcony",
        "Separate bedroom and spacious living room",
        "King-size bed",
        "Luxurious marble bathroom with bathtub",
        "Smart TV in both rooms",
        "Nespresso machine",
        "Butler service",
        "Premium bath products",
      ],
      image: images.cabins.premiumSuite,
      featured: true,
    },
  ],
  amenities: {
    title: "All cabins include",
    items: [
      "Daily cabin service",
      "Premium bedding",
      "Hairdryer",
      "Bathrobe and slippers",
      "Safe",
      "Unlimited Wi-Fi",
    ],
  },
} as const
