import { images } from "./images"

export const cabins = {
  title: "舱房",
  subtitle: "选择您在探险船SH Diana号上的舱房",
  popularBadge: "热门选择",
  selectButton: "询价",
  categories: [
    {
      name: "海景舱",
      size: "20平方米",
      features: ["两个舷窗", "双床或大床", "独立浴室", "智能电视", "迷你吧"],
      image: images.cabins.oceanview,
      featured: false,
    },
    {
      name: "全景窗舱",
      size: "20平方米",
      features: [
        "大型全景窗",
        "双床或大床",
        "独立浴室",
        "智能电视",
        "迷你吧",
      ],
      image: images.cabins.panoramicWindow,
      featured: false,
    },
    {
      name: "阳台舱",
      size: "25平方米",
      features: [
        "私人阳台",
        "双床或大床",
        "带淋浴的独立浴室",
        "智能电视",
        "迷你吧",
        "休息区",
      ],
      image: images.cabins.balcony,
      featured: true,
    },
    {
      name: "全景阳台舱",
      size: "25平方米",
      features: [
        "全景阳台",
        "双床或大床",
        "高级浴室",
        "智能电视",
        "迷你吧",
        "工作区",
      ],
      image: images.cabins.panoramicBalcony,
      featured: true,
    },
    {
      name: "全景阳台初级套房",
      size: "32–36平方米",
      features: [
        "宽敞的全景阳台",
        "独立起居区",
        "特大床",
        "豪华浴室",
        "智能电视",
        "咖啡机",
        "浴袍和拖鞋",
      ],
      image: images.cabins.juniorSuite,
      featured: true,
    },
    {
      name: "全景阳台套房",
      size: "41平方米",
      features: [
        "大型全景阳台",
        "独立卧室和客厅",
        "特大床",
        "带浴缸的大理石浴室",
        "每个房间配备智能电视",
        "Nespresso咖啡机",
        "高级设施",
      ],
      image: images.cabins.suite,
      featured: true,
    },
    {
      name: "全景阳台豪华套房",
      size: "41平方米",
      features: [
        "宽阔的全景阳台",
        "独立卧室和宽敞客厅",
        "特大床",
        "带浴缸的豪华大理石浴室",
        "两个房间均配备智能电视",
        "Nespresso咖啡机",
        "管家服务",
        "高级浴室用品",
      ],
      image: images.cabins.premiumSuite,
      featured: true,
    },
  ],
  amenities: {
    title: "所有舱房均包含",
    items: [
      "每日客房服务",
      "高级寝具",
      "吹风机",
      "浴袍和拖鞋",
      "保险箱",
      "无限Wi-Fi",
    ],
  },
} as const
