import { images } from "../../images"

export const cabins = {
  categories: [
    {
      name: "Oceanview",
      price: "$16,650",
      size: "20 м²",
      capacity: "2",
      features: [
        "Две односпальные или одна двуспальная кровать",
        "Спальня с гостиной зоной",
        "Декоративный камин",
        "Роскошная ванная комната",
      ],
      images: images.cabins.oceanview,
      videos: images.cabinVideos.oceanview,
    },
    {
      name: "Balcony",
      price: "$19,000",
      size: "25 м²",
      capacity: "2-3",
      features: [
        "Приватный балкон 5 м²",
        "Две односпальные или одна двуспальная кровать",
        "Спальня с гостиной зоной",
        "Декоративный камин",
        "Роскошная ванная комната",
      ],
      images: images.cabins.balcony,
      videos: images.cabinVideos.balcony,
    },
    {
      name: "Junior Suite",
      price: "$24,150",
      size: "32-36 м²",
      capacity: "2",
      features: [
        "Приватный балкон 6 м²",
        "Кровать King size",
        "Отдельная гостиная зона",
        "Роскошная ванная комната",
      ],
      images: images.cabins.juniorSuite,
      videos: images.cabinVideos.juniorSuite,
    },
    {
      name: "Suite",
      price: "$28,100",
      size: "41 м²",
      capacity: "2-3",
      features: [
        "Приватный балкон 5 м²",
        "Кровать King size",
        "Отдельная гостиная",
        "Декоративный камин",
        "Роскошная ванная с ванной и душевой кабиной",
      ],
      images: images.cabins.suite,
      videos: images.cabinVideos.suite,
    },
    {
      name: "Premium Suite",
      price: "$32,100",
      size: "41 м²",
      capacity: "2",
      features: [
        "Приватный балкон 8 м²",
        "Кровать King size",
        "Отдельная гостиная",
        "Декоративный камин",
        "Роскошная ванная с ванной и душевой кабиной",
        "Гардеробная",
      ],
      images: images.cabins.premiumSuite,
      videos: images.cabinVideos.premiumSuite,
    },
  ],
} as const
