import { images } from "../../images"

export const cabins = {
  categories: [
    {
      name: "Oceanview",
      price: "$16,650",
      size: "20 平方米",
      capacity: "2",
      features: [
        "两张单人床或一张双人床",
        "带起居区的卧室",
        "火焰效果壁炉",
        "豪华浴室",
      ],
      images: images.cabins.oceanview,
      videos: images.cabinVideos.oceanview,
    },
    {
      name: "Balcony",
      price: "$19,000",
      size: "25 平方米",
      capacity: "2-3",
      features: [
        "5平方米私人阳台",
        "两张单人床或一张双人床",
        "带起居区的卧室",
        "火焰效果壁炉",
        "豪华浴室",
      ],
      images: images.cabins.balcony,
      videos: images.cabinVideos.balcony,
    },
    {
      name: "Junior Suite",
      price: "$24,150",
      size: "32-36 平方米",
      capacity: "2",
      features: [
        "6平方米私人阳台",
        "特大号床",
        "独立起居区",
        "豪华套内浴室",
      ],
      images: images.cabins.juniorSuite,
      videos: images.cabinVideos.juniorSuite,
    },
    {
      name: "Suite",
      price: "$28,100",
      size: "41 平方米",
      capacity: "2-3",
      features: [
        "5平方米私人阳台",
        "特大号床",
        "独立客厅",
        "火焰效果壁炉",
        "豪华套内浴室，配有独立浴缸和淋浴间",
      ],
      images: images.cabins.suite,
      videos: images.cabinVideos.suite,
    },
    {
      name: "Premium Suite",
      price: "$32,100",
      size: "41 平方米",
      capacity: "2",
      features: [
        "8平方米私人阳台",
        "特大号床",
        "独立客厅",
        "火焰效果壁炉",
        "豪华套内浴室，配有独立浴缸和淋浴间",
        "步入式衣橱",
      ],
      images: images.cabins.premiumSuite,
      videos: images.cabinVideos.premiumSuite,
    },
  ],
} as const
