import { images } from "../../images"

export const cabins = {
  categories: [
    {
      name: "Oceanview",
      price: "From $16,650",
      size: "20 m²",
      capacity: "2",
      features: [
        "Two single beds or a double bed",
        "Bedroom with living room area",
        "Flame-effect fireplace",
        "Luxurious bathroom",
      ],
      images: images.cabins.oceanview,
      videos: images.cabinVideos.oceanview,
    },
    {
      name: "Balcony",
      price: "From $19,000",
      size: "25 m²",
      capacity: "2-3",
      features: [
        "5 m² private balcony",
        "Two single beds or a double bed",
        "Bedroom with living room area",
        "Flame-effect fireplace",
        "Luxurious bathroom",
      ],
      images: images.cabins.balcony,
      videos: images.cabinVideos.balcony,
    },
    {
      name: "Junior Suite",
      price: "From $24,150",
      size: "32-36 m²",
      capacity: "2",
      features: [
        "6 m² private balcony",
        "King size bed",
        "Separate living room area",
        "Luxurious en-suite bathroom",
      ],
      images: images.cabins.juniorSuite,
      videos: images.cabinVideos.juniorSuite,
    },
    {
      name: "Suite",
      price: "From $28,100",
      size: "41 m²",
      capacity: "2-3",
      features: [
        "5 m² private balcony",
        "King size bed",
        "Separate living room",
        "Flame-effect fireplace",
        "Luxurious ensuite bathroom with separate bath tub and walk-in shower",
      ],
      images: images.cabins.suite,
      videos: images.cabinVideos.suite,
    },
    {
      name: "Premium Suite",
      price: "From $32,100",
      size: "41 m²",
      capacity: "2",
      features: [
        "8 m² private balcony",
        "King size bed",
        "Separate living room",
        "Flame-effect fireplace",
        "Luxurious ensuite bathroom with separate bath tub and shower",
        "Walk-in wardrobe",
      ],
      images: images.cabins.premiumSuite,
      videos: images.cabinVideos.premiumSuite,
    },
  ],
} as const
