import { images } from "../images"

export const cabins = {
  title: "Каюты",
  subtitle: "Светлые и просторные каюты — «уютный дом вдали от дома»",
  selectButton: "Запросить цену",
  priceNote: "Цены указаны за человека за круиз",
  categories: [
    {
      name: "Oceanview",
      size: "20 м²",
      capacity: "2",
      price: "От $13,780",
      features: [
        "Две односпальные или одна двуспальная кровать",
        "Спальня с гостиной зоной",
        "Декоративный камин",
        "Роскошная ванная комната",
      ],
      images: images.cabins.oceanview,
      videos: images.cabinVideos.oceanview,
    },
    {
      name: "Balcony",
      size: "25 м²",
      capacity: "2-3",
      price: "От $13,780",
      features: [
        "Приватный балкон 5 м²",
        "Две односпальные или одна двуспальная кровать",
        "Спальня с гостиной зоной",
        "Декоративный камин",
        "Роскошная ванная комната",
      ],
      images: images.cabins.balcony,
      videos: images.cabinVideos.balcony,
    },
    {
      name: "Junior Suite",
      size: "32-36 м²",
      capacity: "2",
      price: "От $23,380",
      features: [
        "Приватный балкон 6 м²",
        "Кровать King size",
        "Отдельная гостиная зона",
        "Роскошная ванная комната",
      ],
      images: images.cabins.juniorSuite,
      videos: images.cabinVideos.juniorSuite,
    },
    {
      name: "Suite",
      size: "41 м²",
      capacity: "2-3",
      price: "От $27,280",
      features: [
        "Приватный балкон 5 м²",
        "Кровать King size",
        "Отдельная гостиная",
        "Декоративный камин",
        "Роскошная ванная с ванной и душевой кабиной",
      ],
      images: images.cabins.suite,
      videos: images.cabinVideos.suite,
    },
    {
      name: "Premium Suite",
      size: "41 м²",
      capacity: "2",
      price: "От $31,180",
      features: [
        "Приватный балкон 8 м²",
        "Кровать King size",
        "Отдельная гостиная",
        "Декоративный камин",
        "Роскошная ванная с ванной и душевой кабиной",
        "Гардеробная",
      ],
      images: images.cabins.premiumSuite,
      videos: images.cabinVideos.premiumSuite,
    },
  ],
} as const
