import { images } from "../images"

export const cabins = {
  title: "Staterooms",
  subtitle: "Choose your stateroom aboard the expedition vessel SH Diana",
  selectButton: "Request a quote",
  priceNote: "Prices are quoted per person per cruise",
  categories: [
    {
      name: "Oceanview",
      size: "20 m²",
      capacity: "2",
      price: "From $13,780",
      features: [
        "Two single beds or a double bed",
        "Bedroom with living room area",
        "Flame-effect fireplace",
        "Luxurious bathroom",
      ],
      images: images.cabins.oceanview,
      videos: images.cabinVideos.oceanview,
    },
    {
      name: "Balcony",
      size: "25 m²",
      capacity: "2-3",
      price: "From $13,780",
      features: [
        "5 m² private balcony",
        "Two single beds or a double bed",
        "Bedroom with living room area",
        "Flame-effect fireplace",
        "Luxurious bathroom",
      ],
      images: images.cabins.balcony,
      videos: images.cabinVideos.balcony,
    },
    {
      name: "Junior Suite",
      size: "32-36 m²",
      capacity: "2",
      price: "From $23,380",
      features: [
        "6 m² private balcony",
        "King size bed",
        "Separate living room area",
        "Luxurious en-suite bathroom",
      ],
      images: images.cabins.juniorSuite,
      videos: images.cabinVideos.juniorSuite,
    },
    {
      name: "Suite",
      size: "41 m²",
      capacity: "2-3",
      price: "From $27,280",
      features: [
        "5 m² private balcony",
        "King size bed",
        "Separate living room",
        "Flame-effect fireplace",
        "Luxurious ensuite bathroom with separate bath tub and walk-in shower",
      ],
      images: images.cabins.suite,
      videos: images.cabinVideos.suite,
    },
    {
      name: "Premium Suite",
      size: "41 m²",
      capacity: "2",
      price: "From $31,180",
      features: [
        "8 m² private balcony",
        "King size bed",
        "Separate living room",
        "Flame-effect fireplace",
        "Luxurious ensuite bathroom with separate bath tub and shower",
        "Walk-in wardrobe",
      ],
      images: images.cabins.premiumSuite,
      videos: images.cabinVideos.premiumSuite,
    },
  ],
} as const
