import { images } from "../images"

export const cabins = {
  title: "Cabins",
  subtitle: "Choose your cabin aboard the expedition vessel SH Diana",
  selectButton: "Request a quote",
  priceNote: "Prices are quoted per person per cruise",
  categories: [
    {
      name: "Oceanview D4",
      size: "20 m²",
      capacity: "2",
      price: "From $13,780",
      features: [
        "Two single beds or a double bed",
        "Bedroom with living room area",
        "Flame-effect fireplace",
        "Luxurious bathroom",
      ],
      images: [images.cabins.oceanview, images.cabins.oceanview],
    },
    {
      name: "Oceanview M4",
      size: "20 m²",
      capacity: "2",
      price: "Waiting list",
      features: [
        "Two single beds or a double bed",
        "Bedroom with living room area",
        "Flame-effect fireplace",
        "Luxurious bathroom",
      ],
      images: [images.cabins.panoramicWindow, images.cabins.panoramicWindow],
    },
    {
      name: "Balcony D5",
      size: "25 m²",
      capacity: "2-3",
      price: "From $13,780",
      features: [
        "5 m² private balcony",
        "Two single beds or a double bed",
        "Bedroom with living room area",
        "Flame-effect fireplace",
        "Luxurious bathroom",
      ],
      images: [images.cabins.balcony, images.cabins.balcony],
    },
    {
      name: "Balcony M5",
      size: "25 m²",
      capacity: "2-3",
      price: "From $13,780",
      features: [
        "5 m² private balcony",
        "Two single beds or a double bed",
        "Bedroom with living room area",
        "Flame-effect fireplace",
        "Luxurious bathroom",
      ],
      images: [images.cabins.panoramicBalcony, images.cabins.panoramicBalcony],
    },
    {
      name: "Balcony D6",
      size: "25 m²",
      capacity: "2-3",
      price: "From $13,780",
      features: [
        "5 m² private balcony",
        "Two single beds or a double bed",
        "Bedroom with living room area",
        "Flame-effect fireplace",
        "Luxurious bathroom",
      ],
      images: [images.cabins.balcony, images.cabins.balcony],
    },
    {
      name: "Junior Suite",
      size: "32-36 m²",
      capacity: "2",
      price: "From $23,380",
      features: [
        "6 m² private balcony",
        "King size bed",
        "Separate living room area",
        "Luxurious en-suite bathroom",
      ],
      images: [images.cabins.juniorSuite, images.cabins.juniorSuite],
    },
    {
      name: "Suite",
      size: "41 m²",
      capacity: "2-3",
      price: "From $27,280",
      features: [
        "5 m² private balcony",
        "King size bed",
        "Separate living room",
        "Flame-effect fireplace",
        "Luxurious ensuite bathroom with separate bath tub and walk-in shower",
      ],
      images: [images.cabins.suite, images.cabins.suite],
    },
    {
      name: "Premium Suite",
      size: "41 m²",
      capacity: "2",
      price: "From $31,180",
      features: [
        "8 m² private balcony",
        "King size bed",
        "Separate living room",
        "Flame-effect fireplace",
        "Luxurious ensuite bathroom with separate bath tub and shower",
        "Walk-in wardrobe",
      ],
      images: [images.cabins.premiumSuite, images.cabins.premiumSuite],
    },
  ],
} as const
